### PR TITLE
Updates for blank_webserver to run on port 80

### PR DESCRIPTION
**Pull request by 0-kaladin**
// Still need to return empty page

This gets it running on 80 again.
Still i couldn't get it to return a blank page.  It either was doing a directory listing or if I disabled dir listing then it would return a 403 forbidden (since dir listing isn't allowed).

It seems the piece we are now missing from the old blank_webserver.c is this :

 ```java
// This function will be called by mongoose on every new request.
static int begin_request_handler(struct mg_connection *conn) {
  const struct mg_request_info *request_info = mg_get_request_info(conn);
  char content[100];

  // Prepare the message we're going to send
  int content_length = snprintf(content, sizeof(content), "");

  // Send HTTP reply to the client
  mg_printf(conn,
            "HTTP/1.1 200 OK\r\n"
            "Content-Type: text/plain\r\n"
            "Content-Length: %d\r\n" // Always set Content-Length
            "\r\n"
            "%s",
            content_length, content);

  // Returning non-zero tells mongoose that our function has replied to
  // the client, and mongoose should not send client any more data.
  return 1;
}
```

Unfortunately my limited python knowledge wasn't enough to get that support added back in correctly.  Potentially would be easy for you.

### CODE REVIEW

**Comment by dschuermann** [comment]
Ah sry overlooked it.
I leave this open until someone re-implements the functionality. I have no time currently :/

**Comment by 0-kaladin** [comment]
ok i can always take a stab at it when time allows as well.  Unless @DavisNT has any spare cycles as whatever I do would be a "working" hack.

**Comment by 0-kaladin** [comment]
@dschuermann blank pages now being served.

**Comment by dschuermann** [comment]
thanks!

**Comment by 0-kaladin** [comment]
I updated the 605 pull request in case you didn't see it.

**Comment by 0-kaladin** [comment]
I tried duping your issue not sure if you saw response. Bottom line try
using the latest supersu I mentioned.

**Pull request merged**
