### PR TITLE
Externals

### PR DESCRIPTION
**Pull request by 0-kaladin**
Tried to do this as cleanly as I know how.  This is dnsmasq, tcpdump, and libpcap sync from latest google source.  Then mongoose sync'd from it's latest source.  The rest is adjustments needed to get it all to compile. Tested a build and webserver starts, can still log dns requests and tcpdump etc. 
As stated before the resultant binary apk is about .5mb larger.  Potentially removing more un-needed items from config.h could shrink it down a bit.

### CODE REVIEW

**Comment by dschuermann** [comment]
Awesome work!

**Comment by dschuermann** [comment]
@0-kaladin Does the webserver still deliver blank webpages?

**Comment by 0-kaladin** [comment]
ah good question.  just looked at it and it's listening on 8080 now.  That has to go back to 80. Let me run some more tests see if more needs adjusting.

**Comment by dschuermann** [comment]
Any progress?

**Comment by 0-kaladin** [comment]
I posted the new pull with comments there.

**Pull request merged**
